#!/bin/bash
#
# Halium installer script
# =======================
#
# Copyright (C) 2017 JBBgameich
# Copyright (C) 2017 TheWiseNerd
#
# License: GPLv3
#
# dependencies: qemu binfmt-support qemu-user-static e2fsprogs sudo simg2img

LOCATION="$(dirname "$(readlink -f "$0")")"

# Defaults
export ROOTFS_RELEASE="none"
export INSTALL_MODE="img"

function quiet ( ) {
    cat > /dev/null
}

out=quiet

# Include functions
source $LOCATION/functions/misc.sh

# parse options
while [ -n "$1" ] ; do
	case "$1" in
	"-p")
		shift
		export ROOTFS_RELEASE="$1"
		case $ROOTFS_RELEASE in
		"halium" | "debian-pm" | "reference" | "debian-pm-caf" | "pm" | "neon" | "ut" | "none")
			;;
		*)
			echo "Unsupported post install release! Exiting now"
			exit 1
			;;
		esac
		;;
	"-m" | "--mode")
		shift
		export INSTALL_MODE="$1"
		case $INSTALL_MODE in
		"img" | "dir" )
			;;
		*)
			echo "Unsupported install mode! Exiting now"
			exit 1
			;;
		esac
		;;
	"-v")
		out="cat -"
		;;
	*)
		break
		;;
	esac
	shift
done

# parse positional parameters
if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
	usage
	exit
fi

export ROOTFS_TAR=$1
export AND_IMAGE=$2
if [ ! -f $ROOTFS_TAR ] || [ ! -f $AND_IMAGE ]; then
	usage
	exit
fi

# Check for missing dependencies
if ! init_checks; then
	exit
fi

export ROOTFS_DIR=$(mktemp -d .halium-install-rootfs.XXXXX)
export IMAGE_DIR=$(mktemp -d .halium-install-imgs.XXXXX)

# Logic that depends on the opts being parsed
source $LOCATION/functions/distributions.sh
source $LOCATION/functions/core.sh

# Start installer
echo "Debug: Chosen rootfs is $ROOTFS_TAR"
echo "Debug: Chosen android image is $AND_IMAGE"
echo "Debug: Chosen release is $ROOTFS_RELEASE"
echo

case "$INSTALL_MODE" in
"img")
	echo "I: Writing rootfs into mountable image"
	convert_rootfs_to_img $IMAGE_SIZE 2>&1 | $out
	;;
"dir")
	echo "I: Extracting rootfs"
	convert_rootfs_to_dir 2>&1 | $out
	;;
esac

echo "I: Writing android image into mountable image"
convert_androidimage 2>&1 | $out

echo "I: Running post installation tasks"
post_install $ROOTFS_RELEASE

echo "I: Unmounting images"
unmount

echo "I: Shrinking images"
shrink_images

case "$INSTALL_MODE" in
"img")
	echo "I: Pushing rootfs and android image to /data via ADB"
	if ! flash_img $ROOTFS_RELEASE; then
		echo "Error: Couldn't copy the files to the device, is it connected?"
	fi
	;;
"dir")
	echo "I: Pushing rootfs and android image to /data via ADB"
	if ! flash_dir $ROOTFS_RELEASE; then
		echo "Error: Couldn't copy the files to the device, is it connected?"
	fi
	;;
esac

echo "I: Cleaning up host"
clean

echo "I: Cleaning up device"
clean_device

